### ISSUE TITLE
Generate log file

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/bids_neuropoly#4]
Will help to debug on the user's side.
Notably include:
- dcm2niix version
- convert_dcm2nii.py version (git hashtag)
- Terminal output

save as log.

Use Python's logger

**Comment by alexfoias** [comment]
@jcohenadad Do you want me to implement it ?

**Comment by alexfoias** [comment]
@jcohenadad  I pushed an initial version here: https://github.com/neuropoly/bids_neuropoly/commit/3fbe6a592fe245c7a734db47c835269601f04807

Could you please share with me a Philips dataset to test the warning logging ? Thank you

**Comment by jcohenadad** [comment]
@alexfoias added `duke:mri/sherbrooke/20190111_Sherbrooke03.zip`

**Comment by alexfoias** [comment]
Fixed in https://github.com/neuropoly/bids_neuropoly/pull/6
